kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  GITLAB_OMNIBUS_CONFIG: |
    {{- if .Values.controller.externalUrl }}
    external_url '{{ .Values.controller.externalUrl }}'
    {{- end }}
    {{- if .Values.controller.httpPort }}
    gitlab_rails['gitlab_port'] = {{ .Values.controller.httpPort }}
    {{- end }}
    # Add any other gitlab.rb configuration here, each on its own line
    {{- if .Values.controller.extraConfigs }}
    {{ .Values.controller.extraConfigs | nindent 4 }}
    {{- end }}
    gitlab_rails['gitlab_shell_ssh_port'] = nil