{{/*
Copyright ZeroX.
*/}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.fullname" . -}}
{{- $svcHttpPort := .Values.controller.service.httpPort -}}
{{- if and .Values.ingress.ingressClassName (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.ingressClassName }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  tls:
    {{- if and .Values.ingress.tls ( and .Values.ingress.tls.key .Values.ingress.tls.crt ) }}
    {{- if .Values.ingress.host }}
    - hosts: 
        - {{ .Values.ingress.host }}
      secretName: {{ include "common.fullname" . }}-tls
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.extraTls }}
    {{- toYaml . | nindent 4 -}}
    {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if $svcHttpPort }}
          - path: /
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcHttpPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcHttpPort }}
              {{- end }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: ImplementationSpecific
            {{- end }}
          {{- end }}
    {{- end }}
    {{- range $host := .Values.ingress.extraHosts }}
    - host: {{ $host.host }}
      http:
        paths:
          {{- if and $svcHttpPort $host.paths }}
          {{- range $path := $host.paths }}
          - path: {{ $path.path | default "/" }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcHttpPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcHttpPort }}
              {{- end }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: {{ $path.pathType | default "ImplementationSpecific" }} 
            {{- end }}
          {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
