{{- /*
Copyright ZeroX
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
type: Opaque
data:
  {{- if .Release.IsInstall }}
  GITLAB_ROOT_PASSWORD: {{ .Values.controller.password | default (randAlphaNum 20) | b64enc }}
  {{- else }}
  GITLAB_ROOT_PASSWORD: {{ index ( lookup "v1" "Secret" .Release.Namespace ( include "common.fullname" . ) ).data "GITLAB_ROOT_PASSWORD" | b64dec | b64enc }}
  {{- end }}