# Copyright ZeroX.

# Global define (Require)
global:
  # Full name override
  fullname: "gitlab"
  # Name override
  name: "gitlab"
  # Kube version
  kubeVersion: ""

# Controller
controller: 
  # Kind of controller Deployment, DaemonSet or Both
  kind: "Deployment"


# Role-based access control (RBAC)
rbac:
  # Create RBAC resources
  create: false
  scope: false