# Copyright ZeroX.

# Global define (Require)
global:
  # Full name override
  fullname: "gitlab"
  # Name override
  name: "gitlab"
  # Kube version
  kubeVersion: ""

# Controller
controller: 
  # Kind of controller Deployment, DaemonSet or Both
  kind: "Deployment"