{{/*
Copyright ZeroX.
*/}}
kind: ConfigMap
apiVersion: {{ include "common.capabilities.configMap.apiVersion" . }}
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_DB: {{ default "postgres" .Values.controller.primary.db }}
  POSTGRES_USER: {{ default "root" .Values.controller.primary.username }}
  