{{/*
Copyright ZeroX.
*/}}
{{- $oldSecret := ( lookup "v1" "Secret" .Release.Namespace ( include "common.fullname" . ) ) }}
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if not ( and $oldSecret ( index $oldSecret.data "POSTGRES_PASSWORD" ) ) }}
  POSTGRES_PASSWORD: {{ .Values.controller.primary.password | default (randAlphaNum 20) | b64enc }}
  {{- else }}
  POSTGRES_PASSWORD: {{ index $oldSecret.data "POSTGRES_PASSWORD" | b64dec | b64enc }}
  {{- end }}