{{- if .Values.controller.serviceAccount.create -}}
apiVersion: {{ include "common.capabilities.serviceAccount.apiVersion" . }}
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccount.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
