{{/*
Copyright ZeroX.
*/}}
apiVersion: {{ include "common.capabilities.statefulSet.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{-  include "common.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "common.fullname" . }}
  replicas: {{ default 1 .Values.controller.replicaCount }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.controller.hostNetwork }}
      initContainers:
        - name: {{ include "common.fullname" . }}-copy-certs
        - name: {{ include "common.fullname" . }}-init-chmod-data
      containers:
        - name: {{ include "common.fullname" . }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.controller.registry | default "docker.io" }}/{{ required "require image tag" .Values.controller.image }}:{{ .Values.controller.version | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.pullPolicy | default "IfNotPresent" }}
          ports:
            {{- if .Values.controller.port }}
            - name: postgres
              containerPort: {{ .Values.controller.port }}
              protocol: TCP
            {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          envFrom:
            - configMapRef:
                name: {{ include "common.fullname" . }}
            - secretRef: 
                name: {{ include "common.fullname" . }}
          env:
            {{- if .Values.controller.extraEnvs }}
            {{ toYaml .Values.controller.extraEnvs | nindent 12 }}
            {{- end }}
          {{- if .Values.controller.resources }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
    - apiVersion: {{ include "common.capabilities.persistentVolume.apiVersion" . }}
      kind: PersistentVolumeClaim
      metadata: 
        name: {{ include "common.fullname" . }}
      spec:
      
      
