{{- if .Values.controller.ingress.enabled -}}
{{- $kubeVersion := include "common.capabilities.kubeVersion" . -}}
{{- $fullName := include "common.names.fullname" . -}}
{{- $servicePort := .Values.controller.service.port  -}}
{{- if and .Values.controller.ingress.ingressClassName (not (semverCompare ">=1.18-0" $kubeVersion)) }}
  {{- if not (hasKey .Values.controller.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.controller.ingress.annotations "kubernetes.io/ingress.class" .Values.controller.ingress.ingressClassName }}
  {{- end }}
{{- else if and (hasKey .Values.controller.ingress.annotations "kubernetes.io/ingress.class") (semverCompare ">=1.18-0" $kubeVersion) }}
{{- $_ := unset .Values.controller.ingress.annotations "kubernetes.io/ingress.class" }}
{{- end }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" . | nindent 4 -}}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.controller.ingress.ingressClassName (semverCompare ">=1.18-0" $kubeVersion) }}
  ingressClassName: {{ default "nginx" .Values.controller.ingress.ingressClassName }}
  {{- end }}
  rules:
    {{- range $host := .Values.controller.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 -}}
  {{- end -}}
{{- end -}}