---
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: {{ include "common.capabilities.persistentVolume.apiVersion" . }}
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  {{- if .Values.persistence.annotations }}
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.storageClass }}
  {{- if eq "-" .Values.persistence.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.size }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- end }}
  {{- if .Values.persistence.volumeMode }}
  volumeMode: {{ .Values.persistence.volumeMode }}
  {{- end }}
  volumeName: {{ default (include "common.names.fullname" .) .Values.persistence.volumeName }}
  {{- if .Values.persistence.selector }}
  selector:
    {{- toYaml .Values.persistence.selector | nindent 4 }}
  {{- end }}
{{- end }}