{{/*
Copyright ZeroX.
*/}}
{{- $oldSecret := (lookup (include "common.capabilities.secret.apiVersion" .) "Secret" .Release.Namespace (include "common.fullname" .)) }}
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
type: Opaque
data:
  
  {{- $oldPassword := (index $oldSecret.data "PASSWORD" | b64dec) -}}
  {{- $oldHashedPassword := (index $oldSecret.data "HASHED_PASSWORD" | b64dec) -}}
  {{- if and (not .Values.password) (not .Values.hashedPassword) }}

  {{- else }}
  {{- if .Values.password }}
  PASSWORD: {{ .Values.password | b64enc }}
  {{- end }}
  {{- if .Values.hashedPassword }}
  HASHED_PASSWORD: {{ .Values.hashedPassword | b64enc }}
  {{- end }}
  {{- end }}
