{{/*
Copyright ZeroX.
*/}}
---
{{- $oldSecret := (lookup (include "common.capabilities.secret.apiVersion" .) "Secret" .Release.Namespace (include "common.names.fullname" .)) }}
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
type: Opaque
data:
  {{- if not .Values.emptyPassword }}
  {{- if and (empty .Values.password) (empty .Values.hashedPassword) }}
  {{- if $oldSecret }}
  {{- $oldPassword := (index $oldSecret.data "PASSWORD" | b64dec) }}
  PASSWORD: {{ default (randAlphaNum 10) $oldPassword | b64enc }}
  {{- else }}
  PASSWORD: {{ randAlphaNum 10 | b64enc }}
  {{- end }}
  {{- else }}
  {{- if .Values.password }}
  PASSWORD: {{ .Values.password | b64enc }}
  {{- end }}
  {{- if .Values.hashedPassword }}
  HASHED_PASSWORD: {{ .Values.hashedPassword | b64enc }}
  {{- end }}
  {{- end }}
  {{- if and (empty .Values.sudoPassword) (empty .Values.hashedSudoPassword) }}
  {{- if $oldSecret }}
  {{- $oldSudoPassword := (index $oldSecret.data "SUDO_PASSWORD" | b64dec) }}
  SUDO_PASSWORD: {{ default (randAlphaNum 10) $oldSudoPassword | b64enc }}
  {{- else }}
  SUDO_PASSWORD: {{ randAlphaNum 10 | b64enc }}
  {{- end }}
  {{- else }}
  {{- if .Values.sudoPassword }}
  SUDO_PASSWORD: {{ .Values.sudoPassword | b64enc }}
  {{- end }}
  {{- if .Values.hashedSudoPassword }}
  SUDO_PASSWORD_HASH: {{ .Values.hashedSudoPassword | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
