apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.read.v1.fullname" . }}-svc-headless
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ include "postgres.read.v1.fullname" . }}-svc-headless