# Copyright ZeroX.
apiVersion: v2
name: code-server
description: Code Server helm chart setup
type: application
version: 0.0.1
appVersion: "4.17.1" # linuxserver/code-server:4.17.1
home: https://zeroxsolutions.com
keywords:
  - "code-server"
  - "vscode"
  - "helm"
annotations:
  category: "infrastructure"
maintainers:
  - name: ZeroX.
    url: https://github.com/zeroxsolutions/charts
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common