{{/*
Copyright ZeroX.
*/}}
apiVersion: {{ include "common.capabilities.configMap.apiVersion" . }}
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.config "context" $) | nindent 4 }}