---
{{- if .Values.htpasswd }}
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.names.fullname" . }}-htpasswd
  labels:
    {{- include "common.labels" . | nindent 4 }}
stringData:
  htpasswd: |-
    {{- range $user := .Values.htpasswd }}
    {{ htpasswd $user.username $user.password | toString }}
    {{- end }}
{{- end }}