# Copyright ZeroX.
apiVersion: v2
name: gitlab-ce
description: citLab community helm chart setup
type: application
version: 1.0.0
appVersion: "1.16.0"
home: https://zeroxsolutions.com
keywords:
  - "gitlab"
  - "community"
  - "helm"
annotations:
  category: "infrastructure"
maintainers:
  - name: ZeroX
    url: https://github.com/zeroxsolutions/charts
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common