# Copyright ZeroX.
apiVersion: v2
name: gitlab-ce
description: GitLab community helm chart setup
type: application
version: 0.0.1
appVersion: "16.2.8-ce.0"
home: https://zeroxsolutions.com
keywords:
  - "gitlab"
  - "community"
  - "helm"
annotations:
  category: "infrastructure"
maintainers:
  - name: ZeroX
    url: https://github.com/zeroxsolutions/charts
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common