{{/*
Copyright ZeroX.
*/}}
{{- if .Values.rbac.create -}}
{{- if not .Values.rbac.scope -}}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole

{{- end -}}
{{- end -}}