{{/*
Copyright ZeroX.
*/}}
{{- if and .Values.rbac.create (not .Values.rbac.scope) -}}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
{{- end -}}