---
{{- if .Values.redis-ha.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "gitlab-ce.redis-ha.fullname" . }}
  namespace: {{ include "gitlab-ce.redis-ha.namespace" . }}
data:

{{- end }}