# Copyright ZeroX.
apiVersion: v2
name: postgres
description: PostgreSQL
type: application
version: 0.0.1
appVersion: "13.12"
home: https://zeroxsolutions.com
keywords:
  - "postgres"
  - "database"
  - "helm"
annotations:
  category: "infrastructure"
maintainers:
  - name: ZeroX.
    url: https://github.com/zeroxsolutions/charts
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common