# Copyright ZeroX.

# Global define (Require)
global:
  # Full name override
  fullname: "postgres"
  # Name override
  name: "postgres"
  # Kube version
  kubeVersion: ""

# Controller
controller:
  # Service of controller configuration  
  service:
    # Service type ClusterIP, LoadBalancer, NodePort default (LoadBalancer)
    type: ""
    # PostgreSQL port
    port: 5432

  # Service account configuration
  serviceAccount:
    # Create new service account
    create: true
    # Service account name
    name: ""
    # Service account annotations
    # Key: Value
    annotations: {}