# Copyright ZeroX.

# Global define (Require)
global:
  # Full name override
  fullname: "nginx-ingress"
  # Name override
  name: "nginx-ingress"
  # Kube version
  kubeVersion: ""

# Controller
controller: 
  # Kind of controller Deployment, DaemonSet or Both
  kind: "Deployment"
  # 
  scope:
    # 
    enabled: false


# Role-based access control (RBAC)
rbac:
  # Create RBAC resources
  create: false
  # Scope 
  scope: false