{{/*
Copyright ZeroX.
*/}}
{{- if .Values.controller.pv.create }}
apiVersion: {{ include "common.capabilities.persistentVolume.apiVersion" . }}
kind: PersistentVolume
metadata:
  name: {{ include "common.fullname" . }}
spec:
  storageClassName: {{ .Values.controller.pvc.storageClassName | default "" }} 
  claimRef:
    name: {{ .Values.controller.pv.claimRef.name | default ( include "common.fullname" . )  }}
    namespace: {{ .Values.controller.pv.claimRef.namespace | default .Release.Namespace }}
{{- end }}