{{/*
Copyright ZeroX.
*/}}
{{- $oldSecret := ( lookup "v1" "Secret" .Release.Namespace ( include "common.fullname" . ) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
type: Opaque
data:
  {{- if not ( and $oldSecret ( index $oldSecret.data "GITLAB_ROOT_PASSWORD" ) ) }}
  GITLAB_ROOT_PASSWORD: {{ .Values.controller.password | default (randAlphaNum 20) | b64enc }}
  {{- else }}
  GITLAB_ROOT_PASSWORD: {{ index $oldSecret.data "GITLAB_ROOT_PASSWORD" | b64dec | b64enc }}
  {{- end }}