apiVersion: v2
name: verdaccio
description: Verdaccio is a lightweight private npm proxy registry built in Node.js
icon: file://./icon.png
type: application
version: 0.0.1
appVersion: 6.x-next
home: https://zeroxsolutions.com
keywords:
  - "registry"
  - "verdaccio"
  - "helm"
annotations:
  category: "application"
maintainers:
  - name: ZeroX.
    url: https://github.com/zeroxsolutions/charts
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common
