---
{{/*
Copyright ZeroX.
*/}}
{{- if .Values.controller.serviceAccount.create }}
apiVersion: {{ include "common.capabilities.serviceAccount.apiVersion" . }}
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccount.name" . }}
  {{- if .Values.controller.serviceAccount.annotations }}
  annotations: 
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- if or .Values.controller.serviceAccount.imagePullSecretName .Values.controller.serviceAccount.imagePullSecretsNames }}
imagePullSecrets:
{{- end }}
  {{- if .Values.controller.serviceAccount.imagePullSecretName }}
  - name: {{ .Values.controller.serviceAccount.imagePullSecretName}}
  {{- end }}

  {{- if .Values.controller.serviceAccount.imagePullSecretsNames }}
  {{- range .Values.controller.serviceAccount.imagePullSecretsNames }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}