---
{{ if and (not .Values.defaultTLS.secret) (.Values.defaultTLS.cert) (.Values.defaultTLS.key) }}
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "nginx-ingress.defaultTLSName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.defaultTLS.cert }}
  tls.key: {{ .Values.defaultTLS.key }}
{{- end }}