---
{{/*
Copyright ZeroX.
*/}}
{{- if and .Values.controller.autoscaling.enabled (or (eq .Values.controller.kind "deployment") (eq .Values.controller.kind "both")) (.Capabilities.APIVersions.Has (include "common.capabilities.autoscaling.apiVersion" .)) }}
apiVersion: {{ include "common.capabilities.autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nginx-ingress.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
	{{- if .Values.controller.autoscaling.annotations }}
  annotations:
		{{- toYaml .Values.controller.autoscaling.annotations | nindent 4 }}
	{{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ include "nginx-ingress.controller.fullname" . }}
  minReplicas: {{ .Values.controller.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.controller.autoscaling.maxReplicas }}
	{{- if .Values.controller.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.controller.autoscaling.behavior | nindent 4 }}
	{{- end }}
  metrics:
    {{- if .Values.controller.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.controller.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.controller.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.controller.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}