---
{{- if .Values.reportIngressStatus.enableLeaderElection }}
apiVersion: {{ include "common.capabilities.configMap.apiVersion" . }}
kind: ConfigMap
metadata:
  name: {{ include "nginx-ingress.leaderElectionName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- if .Values.reportIngressStatus.annotations }}
  annotations:
    {{- toYaml .Values.reportIngressStatus.annotations | nindent 4 }}
  {{- end }}
{{- end }}