---
{{/*
Copyright ZeroX.
*/}}
{{ if .Values.ingressClass.create }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: IngressClass
metadata:
  name: {{ .Values.ingressClass.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- if .Values.ingressClass.setAsDefaultIngress }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: nginx.org/ingress-controller
{{- end }}