{{- if and .Values.rbac .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nginx-ingress.fullname" . }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nginx-ingress.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "nginx-ingress.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}