{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "nginx-ingress.fullname" . }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - k8s.nginx.org
    resources:
      - virtualserverroutes
    verbs:
      - list
      - watch
  - apiGroups:
      - k8s.nginx.org
    resources:
      - policies
    verbs:
      - get
      - list
      - watch
  - apiGroups: 
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
    resourceNames:
      - {{ default "nginx-ingress" .Values.controller.ingressClass }}
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
      - k8s.nginx.org
    resources: 
      - virtualservers
    verbs:
      - list
      - watch
  - apiGroups:
      - k8s.nginx.org
    resources: 
      - transportservers
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
{{- end }}