{{- if .Values.controller.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: {{ default "kubernetes.io/tls" | .Values.controller.secret.type }}
data:
    {{- if .Values.controller.secret.tls.crt }}
    tls.crt: {{ .Values.controller.secret.tls.crt | b64enc }}
    {{- end }}
    {{- if .Values.controller.secret.tls.key }}
    tls.key: {{ .Values.controller.secret.tls.key | b64enc }}
    {{- end }}
{{- end }}