apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-ingress.fullname" . }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
  type: {{ default "LoadBalancer" .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "nginx-ingress.selectorLabels" . | nindent 4 }}
