---
{{- if .Values.service.create }}
apiVersion: {{ include "common.capabilities.service.apiVersion" . }}
kind: Service
metadata:
  name: {{ include "nginx-ingress.service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.service.extraLabels }}
    {{- toYaml .Values.service.extraLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if hasKey .Values.service "allocateLoadBalancerNodePorts" }}
  allocateLoadBalancerNodePorts: {{ .Values.service.allocateLoadBalancerNodePorts }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies: {{ .Values.service.ipFamilies }}
  {{- end }}
  ports:
    {{- if .Values.service.customPorts }}
    {{- toYaml .Values.service.customPorts | nindent 4 }}
    {{ end }}
    {{- if .Values.service.httpPort.enable }}
    - port: {{ .Values.service.httpPort.port }}
      targetPort: {{ .Values.service.httpPort.targetPort }}
      protocol: TCP
      name: http
      {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.httpPort.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.httpsPort.enable }}
    - port: {{ .Values.service.httpsPort.port }}
      targetPort: {{ .Values.service.httpsPort.targetPort }}
      protocol: TCP
      name: https
      {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.httpsPort.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
{{- end }}