{{/*
Copyright ZeroX.
*/}}
{{- if .Values.persistence.enabled }}
apiVersion: {{ include "common.capabilities.persistentVolume.apiVersion" . }}
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
spec:
  {{- if .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- end }}
  storageClassName: {{ .Values.persistence.storageClassName | default "" }} 
  volumeName: {{ include "common.names.fullname" . | default .Values.persistence.volumeName }}
  {{- if .Values.persistence.selector }}
  selector:
    {{- toYaml .Values.persistence.selector | nindent 4 }}
  {{- end }}
{{- end }}